### ISSUE TITLE
Man how can i start a program at window manages startup

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [mcpcpc/xwm#23]
More precisely the dmenu program and tint2 too and rofi because your window manager liked to me and i want to use it you should make some kind of first user guide

**Comment by soyDESKTOP68A2MRFT** [comment]
I mean at window manager startup

**Comment by mcpcpc** [comment]
Hi @soyDESKTOP68A2MRFT:

Regarding autostart, the functionality can easily be patched in (see the example in the link below).  i dont have access to an environment to test if it works with the latest xwm version at the moment, but i am confident it would be pretty easy to adapt.  

https://github.com/Inesgor/xwm-community/blob/main/patches/autostart.diff

As for a user guide, I was hoping that further documentation and feature enhancement would remain community driven.  With that in mind, I would be open to creating a platform to host such content.

**Comment by soyDESKTOP68A2MRFT** [comment]
And how can i have a taskbar working ?????

**Comment by soyDESKTOP68A2MRFT** [comment]
And some themes

**Comment by mcpcpc** [comment]
> And how can i have a taskbar working ?????

Depends on which taskbar you plan on using. I would refer to the README.md in *xbar*, which describes the typical start process for most taskbar/statusbar programs. Note that using the `.xinitrc` could also be an alternative way of auto-starting a program without patching *xwm*.  

> And some themes

If I have time next week, i will try to put together a few minimal “ricing” examples. In the meantime, i have linked one ricing example i created the past and posted on Reddit (programs used are linked in the comment thread). 

References:
* (xbar) https://github.com/mcpcpc/xbar
* (typical xinitrc sample) https://github.com/bourgeoisor/dotfiles/blob/main/xinitrc
* (minimal ricing example) https://www.reddit.com/r/unixporn/comments/klt90j/xwm_mornings_are_for_coffee_and_contemplation/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
